# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matprod <- function(amat, bmat) {
    .Call(`_quasipoissonprobs_matprod`, amat, bmat)
}

mattridotprod <- function(amat, bmat, cmat) {
    .Call(`_quasipoissonprobs_mattridotprod`, amat, bmat, cmat)
}

mattridotprod2 <- function(amat, bmat, cmat) {
    .Call(`_quasipoissonprobs_mattridotprod2`, amat, bmat, cmat)
}

lambdakfactorial_alt3 <- function(L, eL, maxy) {
    .Call(`_quasipoissonprobs_lambdakfactorial_alt3`, L, eL, maxy)
}

obs_min_expected <- function(L, maxy) {
    .Call(`_quasipoissonprobs_obs_min_expected`, L, maxy)
}


